# Generated by Django 6.1 on 2026-08-09 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_for', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('target_count', models.PositiveSmallIntegerField(default=0)),
                ('topics_discovered', models.PositiveSmallIntegerField(default=0)),
                ('articles_published', models.PositiveSmallIntegerField(default=0)),
                ('articles_held', models.PositiveSmallIntegerField(default=0)),
                ('articles_rejected', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('query', models.CharField(blank=True, max_length=300)),
                ('heat_score', models.FloatField(default=0.0)),
                ('source_count', models.PositiveSmallIntegerField(default=0)),
                ('domain_count', models.PositiveSmallIntegerField(default=0)),
                ('discovered_for', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('selected', 'Selected for writing'), ('written', 'Article written'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='discovered', max_length=20)),
                ('skip_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='news.category')),
            ],
            options={
                'ordering': ['-heat_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('raw_content', models.TextField(blank=True)),
                ('relevance', models.FloatField(default=0.0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='news.topic')),
            ],
            options={
                'ordering': ['-relevance'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=270, unique=True)),
                ('summary', models.CharField(blank=True, max_length=400)),
                ('body', models.TextField(help_text='Plain text; blank lines separate paragraphs.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('needs_review', 'Needs human review'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('review_notes', models.TextField(blank=True)),
                ('max_ngram_overlap', models.FloatField(default=0.0)),
                ('longest_common_run', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.category')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.topic')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='news.article')),
            ],
            options={
                'ordering': ['domain'],
                'constraints': [models.UniqueConstraint(fields=('article', 'url'), name='unique_attribution_per_article')],
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('fingerprint', 'discovered_for'), name='unique_topic_fingerprint_per_day'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('topic', 'url'), name='unique_source_url_per_topic'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='news_articl_status_dad29a_idx'),
        ),
    ]
