# Generated by Django 6.1 on 2026-08-09 11:24

import django.db.models.deletion
import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=news.models.article_image_path)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('licence', models.CharField(blank=True, max_length=80)),
                ('licence_url', models.URLField(blank=True, max_length=500)),
                ('source_page', models.URLField(blank=True, max_length=1000)),
                ('provider', models.CharField(blank=True, max_length=60)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.article')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
